version: '3.7'
services:
  web:
    image: nginx:latest
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB=mule:
      POSTGRES_USER=ade:
      POSTGRES_PASSWORD=s7x8c6h9:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
