version: '3.7'
services:
  web:
    images: nginx
    build: . 
    depends_on:
      - db
    ports:
      - "5000:80"
  db:
    image: postgres
    #environment:
    #  db:
    #  user:
    #  pass:
